// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYgugPPbX5HTD0FP3tp8K0NLsTrAPBLaE',
    appId: '1:707404299408:web:010d49965e7295525bec15',
    messagingSenderId: '707404299408',
    projectId: 'studyhub-606c9',
    authDomain: 'studyhub-606c9.firebaseapp.com',
    storageBucket: 'studyhub-606c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqWCi52WR6NqCooFmybCWC-FuwitxDD6U',
    appId: '1:707404299408:android:2e266997dfc46b035bec15',
    messagingSenderId: '707404299408',
    projectId: 'studyhub-606c9',
    storageBucket: 'studyhub-606c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs_kz52MsJsCyLDl1RKxqoVOMcD64X6Ng',
    appId: '1:707404299408:ios:59ed41232dc9627a5bec15',
    messagingSenderId: '707404299408',
    projectId: 'studyhub-606c9',
    storageBucket: 'studyhub-606c9.firebasestorage.app',
    iosBundleId: 'com.example.studyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs_kz52MsJsCyLDl1RKxqoVOMcD64X6Ng',
    appId: '1:707404299408:ios:59ed41232dc9627a5bec15',
    messagingSenderId: '707404299408',
    projectId: 'studyhub-606c9',
    storageBucket: 'studyhub-606c9.firebasestorage.app',
    iosBundleId: 'com.example.studyhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYgugPPbX5HTD0FP3tp8K0NLsTrAPBLaE',
    appId: '1:707404299408:web:29d5c1a04eae15a95bec15',
    messagingSenderId: '707404299408',
    projectId: 'studyhub-606c9',
    authDomain: 'studyhub-606c9.firebaseapp.com',
    storageBucket: 'studyhub-606c9.firebasestorage.app',
  );
}
